# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: twitter_post
  username: root
  password: 
  host: localhost
  pool: 10
  timeout: 5000
  #socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  database: twitter_post_test
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: twitter_post_prod
  username: t4dev
  password: 
  host: localhost
  pool: 10
  timeout: 5000


cucumber:
  <<: *test